# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 22:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
